/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_xyz_accel_state                11
#define gattdb_trh_state                      15
#define gattdb_gps_lat_long_state             19
#define gattdb_manufacturer_name_string       23
#define gattdb_system_id                      25
#define gattdb_device_name                    28
#define gattdb_ota_control                    33


#endif // __GATT_DB_H
