/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_xyz_accel_state                11
#define gattdb_heartbeat_state                15
#define gattdb_manufacturer_name_string       19
#define gattdb_system_id                      21
#define gattdb_device_name                    24
#define gattdb_temperature_measurement        29
#define gattdb_temperature_type               32
#define gattdb_intermediate_temperature       34
#define gattdb_measurement_interval           37
#define gattdb_valid_range                    39
#define gattdb_ota_control                    42


#endif // __GATT_DB_H
